# Generated by Django 4.1.7 on 2024-11-01 11:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('additional_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='доп. телефон')),
                ('additional_email', models.CharField(blank=True, max_length=150, verbose_name='доп. email')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адерс')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='факс')),
                ('insta', models.URLField(max_length=250, verbose_name='Инстаграмм')),
                ('ok', models.URLField(max_length=250, verbose_name='Однокласники')),
                ('fb', models.URLField(max_length=250, verbose_name='Facebook')),
                ('vk', models.URLField(max_length=250, verbose_name='В Контакте')),
            ],
            options={
                'verbose_name': 'Контакты предприятия',
                'verbose_name_plural': 'Контакты предприятия',
            },
        ),
    ]
