# Generated by Django 4.1.7 on 2024-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='fb',
            field=models.URLField(blank=True, max_length=250, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='insta',
            field=models.URLField(blank=True, max_length=250, verbose_name='Инстаграмм'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ok',
            field=models.URLField(blank=True, max_length=250, verbose_name='Однокласники'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.URLField(blank=True, max_length=250, verbose_name='В Контакте'),
        ),
    ]
