# Generated by Django 4.1.7 on 2024-11-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures_news', verbose_name='Изображение'),
        ),
    ]
