# Generated by Django 4.1.7 on 2024-12-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Интегратор')),
                ('merchant_login', models.CharField(db_index=True, max_length=200, verbose_name='Наименование магазина')),
                ('password1', models.CharField(max_length=128, verbose_name='Пароль #1')),
                ('password2', models.CharField(max_length=128, verbose_name='Пароль #2')),
            ],
            options={
                'verbose_name': 'Настройка платежей',
                'verbose_name_plural': 'Настройка платежей',
            },
        ),
    ]
