# Generated by Django 4.1.7 on 2024-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_paymentsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetup',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Тестовое подключение'),
        ),
    ]
