# Generated by Django 4.1.7 on 2025-04-10 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_paymentsetup_is_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('max_cart_weght', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальный вес корзины, кг.')),
            ],
            options={
                'verbose_name': 'Настройки предприятия',
                'verbose_name_plural': 'Настройка предприятия',
            },
        ),
    ]
