# Generated by Django 4.1.7 on 2025-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_enterprisesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('link', models.URLField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Настройка интеграции',
                'verbose_name_plural': 'Настройки интеграции',
            },
        ),
    ]
