# Generated by Django 4.1.7 on 2025-04-24 11:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_integrationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('content', models.TextField(blank=True, verbose_name='Содержание обращения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('reviewed', 'Рассмотренно')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
