# Generated by Django 4.1.7 on 2025-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0010_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='login',
            field=models.CharField(blank=True, max_length=350, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email'),
        ),
    ]
