# Generated by Django 4.1.7 on 2025-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='insta',
            field=models.URLField(blank=True, max_length=250, verbose_name='Youtube'),
        ),
    ]
