# Generated by Django 4.1.7 on 2024-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('796', 'штук'), ('163', 'грамм'), ('166', 'кг')], db_index=True, default='грамм', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
