# Generated by Django 4.1.7 on 2024-11-12 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_department'),
        ('prices', '0002_alter_price_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('start_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата начала действия')),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания действия')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_prices', to='enterprise.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Цена доставки',
                'verbose_name_plural': 'Цены доставки',
            },
        ),
    ]
