# Generated by Django 4.1.7 on 2025-04-23 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('header_template', models.TextField(blank=True, verbose_name='Заголовок письма')),
                ('footer_template', models.TextField(blank=True, verbose_name='Подвал письма')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=1024, verbose_name='Email получателя')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Тема')),
                ('html_content', models.TextField(verbose_name='Содержание письма')),
                ('sent_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Исходящие письма',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('by_default', 'По умолчанию')], db_index=True, max_length=50, verbose_name='Событие')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Тема письма')),
                ('notification', models.TextField(blank=True, verbose_name='Содержание письма')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to='mailings.notifytemplate', verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('use_up', models.BooleanField(db_index=True, default=True, verbose_name='использовать')),
                ('notify', models.CharField(choices=[('clients', 'Клиентов'), ('users', 'Пользователей'), ('both', 'Клиентов и пользователей')], default='both', max_length=20, verbose_name='Уведомлять')),
                ('notification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mailings.notificationtype', verbose_name='тип уведомления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка уведомления',
                'verbose_name_plural': 'Найстройка уведомлений',
            },
        ),
        migrations.CreateModel(
            name='MailingOfLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование рассылки')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Тема рассылки')),
                ('content', models.TextField(blank=True, verbose_name='Содержание письма')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('sent', 'К отправке'), ('new', 'Новая')], db_index=True, default='new', max_length=20, verbose_name='Статус рассылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_of_letter_templates', to='mailings.notifytemplate', verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=1024, verbose_name='Email')),
                ('mailing_of_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailings.mailingofletters', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
