# Generated by Django 4.1.7 on 2024-11-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_department'),
        ('orders', '0005_order_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_oders', to='enterprise.department', verbose_name='Подразделение'),
        ),
    ]
