# Generated by Django 4.1.7 on 2025-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddresses',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
